// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcD4dCEuDlCemww_jUOA5wmR_v5UoZUq0',
    appId: '1:147615733841:web:b04f56d86030df729c8070',
    messagingSenderId: '147615733841',
    projectId: 'lastnostatefull',
    authDomain: 'lastnostatefull.firebaseapp.com',
    databaseURL: 'https://lastnostatefull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lastnostatefull.firebasestorage.app',
    measurementId: 'G-18EXL8LQ4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVrJ5AaRk1hR4CDmhkvTjbFxQ65GgrDo0',
    appId: '1:147615733841:android:f563ecdb90a1c2da9c8070',
    messagingSenderId: '147615733841',
    projectId: 'lastnostatefull',
    databaseURL: 'https://lastnostatefull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lastnostatefull.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjdkmubGsdI2xqvxnszfFrkGcaUkqQFA',
    appId: '1:147615733841:ios:cf02de05a4487ca39c8070',
    messagingSenderId: '147615733841',
    projectId: 'lastnostatefull',
    databaseURL: 'https://lastnostatefull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lastnostatefull.firebasestorage.app',
    iosBundleId: 'com.example.lastNostatefull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjdkmubGsdI2xqvxnszfFrkGcaUkqQFA',
    appId: '1:147615733841:ios:cf02de05a4487ca39c8070',
    messagingSenderId: '147615733841',
    projectId: 'lastnostatefull',
    databaseURL: 'https://lastnostatefull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lastnostatefull.firebasestorage.app',
    iosBundleId: 'com.example.lastNostatefull',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcD4dCEuDlCemww_jUOA5wmR_v5UoZUq0',
    appId: '1:147615733841:web:05322359c5ad89989c8070',
    messagingSenderId: '147615733841',
    projectId: 'lastnostatefull',
    authDomain: 'lastnostatefull.firebaseapp.com',
    databaseURL: 'https://lastnostatefull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lastnostatefull.firebasestorage.app',
    measurementId: 'G-WREGTD6HKH',
  );
}
